_meta: {
    hostvars: {}
}
all: {
    children: [
        hgx
    ]
}
hgx: {
    vars: {
        os: rhel_9
        primary-cluster-name: Detroit
        secondary-cluster-name: Austin
        ansible_user: root
        ansible_connection: ssh
        ansible_ssh_private_key_file: ${PVC_ROOT_KEY}
    }
    children: [base]
}
base: {
    vars: {
        cloudera_username: ${CLOUDERA_USERNAME}
        cloudera_password: ${CLOUDERA_PASSWORD}
        realm_name: ${REALM_NAME}
        ipa_server_host:   ${IPA_SERVER_HOST}
        the_pwd: ${THE_PWD}
        host-name-range: "base-0[1-2]."${KRB_DOMAIN}
        host-template-ref-name: base-primary-cluster
    }
    hosts: [
        172.19.18.148
        172.19.18.150
        172.19.18.151
        172.19.18.152
        172.19.18.153
        172.19.18.154
    ]
    children: [cm]
}
cm: {
    vars: {
        cloudera_username: ${CLOUDERA_USERNAME}
        cloudera_password: ${CLOUDERA_PASSWORD}
        realm_name: ${REALM_NAME}
        ipa_server_host:   ${IPA_SERVER_HOST}
        the_pwd: ${THE_PWD}
        host-name-range: "base-0[1-2]."${KRB_DOMAIN}
        host-template-ref-name: base-primary-cluster
    }
    hosts: [
        172.19.18.148
    ]
    children: []
}
workers: {
    vars: {
        cloudera_username: ${CLOUDERA_USERNAME}
        cloudera_password: ${CLOUDERA_PASSWORD}
        realm_name: ${REALM_NAME}
        ipa_server_host:   ${IPA_SERVER_HOST}
        the_pwd: ${THE_PWD}
        host-name-range: "base-0[1-2]."${KRB_DOMAIN}
        host-template-ref-name: base-primary-cluster
    }
    hosts: [
        172.19.18.150
        172.19.18.151
        172.19.18.152
        172.19.18.153
        172.19.18.154
    ]
    children: []
}

